on:
  push: { "branches": ["master"] }

jobs:
  cachix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.1.0

      - name: Install Nix
        uses: cachix/install-nix-action@v12

      - name: Setup Cachix
        uses: cachix/cachix-action@v8
        with:
          name: staskell
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: Run tests
        run: ./test.sh
